/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontFamily: {
        // In React Native each expo-google-fonts weight is registered as its own
        // family name (e.g. HankenGrotesk_700Bold). RN selects a font by exact
        // family name only — it does NOT combine fontFamily + fontWeight to pick a
        // file. So `font-sans`/`font-mono` must point at a real loaded family name,
        // and each weight is exposed as a dedicated alias to be applied explicitly.
        sans: [
          'HankenGrotesk_400Regular',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
        'sans-medium': [
          'HankenGrotesk_500Medium',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
        'sans-semibold': [
          'HankenGrotesk_600SemiBold',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
        'sans-bold': [
          'HankenGrotesk_700Bold',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
        mono: [
          'JetBrainsMono_400Regular',
          'ui-monospace',
          'SFMono-Regular',
          'monospace',
        ],
      },
      colors: {
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f4',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#444748',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f0f1f1',
        outline: '#747878',
        'outline-variant': '#c4c7c7',
        'surface-tint': '#5f5e5e',
        primary: '#121213',
        'on-primary': '#ffffff',
        'primary-container': '#272727',
        'on-primary-container': '#8f8e8d',
        'inverse-primary': '#c8c6c5',
        secondary: '#5e5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1dfdf',
        'on-secondary-container': '#636262',
        tertiary: '#111312',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#252726',
        'on-tertiary-container': '#8d8e8d',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e4e2e1',
        'primary-fixed-dim': '#c8c6c5',
        'on-primary-fixed': '#1b1c1c',
        'on-primary-fixed-variant': '#474746',
        'secondary-fixed': '#e4e2e2',
        'secondary-fixed-dim': '#c7c6c6',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#464747',
        'tertiary-fixed': '#e2e3e1',
        'tertiary-fixed-dim': '#c6c7c5',
        'on-tertiary-fixed': '#1a1c1b',
        'on-tertiary-fixed-variant': '#454746',
        background: '#f9f9f9',
        'on-background': '#1a1c1c',
        'surface-variant': '#e2e2e2',
        'accent-active': '#1a1a1a',
        'surface-error': '#fff5f5',
        'text-error': '#c53030',
        'slate-deep': '#0f172a',
        'soft-gray': '#e2e8f0',
        'diff-added': '#f6efe1',
        'diff-added-fg': '#6b5e3f',
        'diff-added-outline': '#e7d9b8',
        'diff-removed': '#ececed',
        'diff-removed-fg': '#8e8f90',
      },
      fontSize: {
        wordmark: [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.04em', fontWeight: '700' },
        ],
        tagline: [
          '18px',
          { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '400' },
        ],
        'headline-lg': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        button: ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'label-caps': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' },
        ],
      },
    },
  },
  plugins: [],
}
